/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/contrats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste les contrats de l'assuré connecté
         * @description Réservé aux assurés. Renvoie les contrats actifs et échus depuis moins de deux ans.
         */
        get: operations["listerMesContrats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste et recherche les dossiers visibles
         * @description Le périmètre dépend du rôle (section 2.9) : l'assuré voit ses dossiers, le gestionnaire son
         *     portefeuille, le responsable son équipe, l'expert les dossiers de ses missions.
         *     Tri par échéance de décision croissante, puis par date de déclaration décroissante.
         */
        get: operations["rechercherSinistres"];
        put?: never;
        /**
         * Déclare un sinistre
         * @description Crée un dossier au statut `DECLARE`. Marque la déclaration tardive (RG-01) et affecte un
         *     gestionnaire (RG-07). L'en-tête `Idempotency-Key` évite les doublons en cas de double envoi.
         */
        post: operations["declarerSinistre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulte un dossier
         * @description Pour un expert, seuls les champs utiles à l'expertise sont renseignés.
         */
        get: operations["consulterSinistre"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/recevabilite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accepte ou refuse la recevabilité d'un dossier déclaré
         * @description Acceptation si RG-02 et RG-03 sont satisfaites ; un refus exige un motif.
         */
        post: operations["deciderRecevabilite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/demandes-pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demande des pièces complémentaires à l'assuré
         * @description Le dossier passe au statut `EN_ATTENTE_PIECES` et l'assuré est notifié.
         */
        post: operations["demanderPieces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/reaffectation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confie le dossier à un autre gestionnaire
         * @description Réservé au responsable de l'équipe.
         */
        post: operations["reaffecterSinistre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/reouverture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rouvre un dossier clos
         * @description Possible au plus deux ans après la clôture (RG-10).
         */
        post: operations["rouvrirSinistre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/historique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chronologie du dossier
         * @description Construite à partir du journal d'audit, du plus récent au plus ancien.
         */
        get: operations["consulterHistorique"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste les pièces d'un dossier
         * @description Toutes les pièces visibles par l'utilisateur, avec leur statut d'analyse.
         */
        get: operations["listerPieces"];
        put?: never;
        /**
         * Dépose une pièce justificative
         * @description Le type réel est vérifié sur le contenu, la taille est limitée à 10 Mo, puis le fichier est
         *     analysé par l'antivirus (RG-12). La pièce n'est consultable qu'une fois jugée saine.
         */
        post: operations["deposerPiece"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pieces/{pieceId}/contenu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Télécharge une pièce
         * @description Redirige vers une URL présignée valable 60 secondes. La consultation est tracée.
         */
        get: operations["telechargerPiece"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Missionne un expert
         * @description Le dossier passe au statut `EN_EXPERTISE`. Obligatoire au-delà du seuil d'expertise (RG-04).
         */
        post: operations["missionnerExpert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste les missions de l'expert connecté
         * @description Un expert ne voit que ses propres missions.
         */
        get: operations["listerMesMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{missionId}/rapport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Enregistre le brouillon du rapport
         * @description Remplace le brouillon. Impossible après le dépôt.
         */
        put: operations["enregistrerBrouillonRapport"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{missionId}/rapport/depot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dépose le rapport, de façon définitive
         * @description Le dossier revient au statut `EN_INSTRUCTION`. Le rapport n'est plus modifiable.
         */
        post: operations["deposerRapport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinistres/{sinistreId}/propositions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calcule et crée la proposition d'indemnité
         * @description Indemnité = min(dommage retenu − vétusté ; plafond) − franchise, jamais négative (RG-05).
         *     Exige un rapport d'expertise si l'estimation dépasse le seuil d'expertise (RG-04).
         */
        post: operations["creerProposition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propositions/{propositionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulte une proposition ou une offre
         * @description L'assuré titulaire y consulte le détail de l'offre qui lui est faite.
         */
        get: operations["consulterProposition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propositions/{propositionId}/envoi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envoie la proposition
         * @description Jusqu'au seuil de double validation, l'offre part directement à l'assuré (`OFFRE_ENVOYEE`).
         *     Au-delà, elle est soumise à un responsable (`EN_VALIDATION`, RG-06).
         */
        post: operations["envoyerProposition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Propositions en attente de validation
         * @description Réservé aux responsables ; limité à leur équipe.
         */
        get: operations["listerValidationsEnAttente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propositions/{propositionId}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valide une proposition au-delà du seuil
         * @description Le valideur doit être différent de l'auteur de la proposition (RG-06). L'offre part à l'assuré.
         */
        post: operations["validerProposition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propositions/{propositionId}/rejet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejette une proposition
         * @description Le commentaire est obligatoire ; la proposition revient au gestionnaire.
         */
        post: operations["rejeterProposition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propositions/{propositionId}/acceptation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * L'assuré accepte l'offre
         * @description Le dossier passe au statut `ACCEPTEE` et l'ordre de virement est émis (RG-14).
         */
        post: operations["accepterOffre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propositions/{propositionId}/contestation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * L'assuré conteste l'offre
         * @description Le motif est obligatoire. Le dossier revient au statut `EN_INSTRUCTION` (RG-14).
         */
        post: operations["contesterOffre"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paiements/retours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reçoit le statut d'un ordre de virement
         * @description Appelé par le système de paiement. Authentifié par une signature HMAC-SHA256 du corps,
         *     transmise dans l'en-tête `X-Signature`. Idempotent : un même retour peut être reçu deux fois.
         */
        post: operations["enregistrerRetourPaiement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pilotage/indicateurs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicateurs de l'équipe ou du portefeuille
         * @description Le gestionnaire voit son portefeuille, le responsable son équipe.
         */
        get: operations["consulterIndicateurs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parametres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulte les paramètres métier
         * @description Réservé à l'administrateur.
         */
        get: operations["consulterParametres"];
        /**
         * Modifie les paramètres métier
         * @description S'applique aux nouveaux dossiers. Chaque modification est tracée.
         */
        put: operations["modifierParametres"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulte le journal d'audit
         * @description Réservé à l'administrateur. Du plus récent au plus ancien.
         */
        get: operations["consulterJournalAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Montant en euros, deux décimales, point décimal (ADR-012)
         * @example 3876.00
         */
        Montant: string;
        /**
         * Format: int64
         * @description Version du dossier ou de la proposition lue par le client (RG-13)
         */
        Version: number;
        /**
         * @description Statut du dossier (section 1.3)
         * @enum {string}
         */
        Statut: "DECLARE" | "EN_INSTRUCTION" | "EN_ATTENTE_PIECES" | "EN_EXPERTISE" | "PROPOSITION" | "EN_VALIDATION" | "OFFRE_ENVOYEE" | "ACCEPTEE" | "INDEMNISE" | "REFUSE" | "CLASSE_SANS_SUITE" | "CLOS";
        /**
         * @description Garantie concernée par le sinistre
         * @enum {string}
         */
        TypeGarantie: "DEGAT_DES_EAUX" | "INCENDIE" | "VOL" | "BRIS_DE_GLACE" | "TEMPETE" | "AUTO_COLLISION" | "AUTO_VANDALISME";
        /**
         * @description Signal posé sur un dossier
         * @enum {string}
         */
        Drapeau: "DECLARATION_TARDIVE" | "REVUE_FRAUDE";
        /** @description Adresse du lieu du sinistre */
        Adresse: {
            ligne: string;
            codePostal: string;
            commune: string;
        };
        /** @description Personne citée dans un dossier */
        Personne: {
            id: string;
            nom: string;
        };
        /** @description Garantie souscrite dans un contrat */
        Garantie: {
            type: components["schemas"]["TypeGarantie"];
            plafond: components["schemas"]["Montant"];
            franchise: components["schemas"]["Montant"];
            /** @description Taux de vétusté appliqué, en pourcentage */
            tauxVetuste: number;
        };
        /** @description Contrat d'assurance, issu du SI de souscription */
        Contrat: {
            /** Format: uuid */
            id: string;
            /** @example HAB-3391027 */
            numero: string;
            /** @enum {string} */
            type: "HABITATION" | "AUTO";
            /** @example Multirisque habitation */
            libelle: string;
            /** Format: date */
            debut: string;
            /** Format: date */
            fin?: string | null;
            garanties: components["schemas"]["Garantie"][];
        };
        /** @description Données saisies par l'assuré ou le gestionnaire pour déclarer un sinistre */
        DeclarationSinistre: {
            /** Format: uuid */
            contratId: string;
            garantie: components["schemas"]["TypeGarantie"];
            /** Format: date */
            dateSurvenance: string;
            /** Format: date */
            dateConnaissance: string;
            circonstances: string;
            lieu: components["schemas"]["Adresse"];
            tiers?: string | null;
            montantEstime?: components["schemas"]["Montant"];
        };
        /** @description Dossier de sinistre */
        Sinistre: {
            /** Format: uuid */
            id: string;
            /** @example SIN-2026-048213 */
            numero: string;
            version: components["schemas"]["Version"];
            statut: components["schemas"]["Statut"];
            /** Format: uuid */
            contratId?: string;
            assure?: components["schemas"]["Personne"];
            garantie: components["schemas"]["TypeGarantie"];
            /** Format: date */
            dateSurvenance: string;
            /** Format: date */
            dateConnaissance?: string;
            /** Format: date-time */
            declareLe: string;
            circonstances?: string;
            lieu?: components["schemas"]["Adresse"];
            tiers?: string | null;
            montantEstime?: components["schemas"]["Montant"];
            gestionnaire?: components["schemas"]["Personne"];
            /** Format: date */
            echeanceDecision?: string | null;
            drapeaux: components["schemas"]["Drapeau"][];
            /** Format: uuid */
            propositionEnCoursId?: string | null;
        };
        /** @description Ligne de liste de dossiers */
        SinistreResume: {
            /** Format: uuid */
            id: string;
            numero: string;
            statut: components["schemas"]["Statut"];
            garantie: components["schemas"]["TypeGarantie"];
            assureNom: string;
            commune?: string;
            /** Format: date */
            dateSurvenance: string;
            montantEstime?: components["schemas"]["Montant"];
            /** Format: date */
            echeanceDecision?: string | null;
            gestionnaireId?: string | null;
            drapeaux: components["schemas"]["Drapeau"][];
        };
        /** @description Page de dossiers */
        PageSinistres: {
            elements: components["schemas"]["SinistreResume"][];
            curseurSuivant?: string | null;
        };
        /** @description Décision du gestionnaire sur la recevabilité */
        DecisionRecevabilite: {
            /** @enum {string} */
            decision: "ACCEPTEE" | "REFUSEE";
            /** @description Obligatoire si la décision est REFUSEE */
            motif?: string;
            version: components["schemas"]["Version"];
        };
        /** @description Pièces demandées à l'assuré */
        DemandePieces: {
            pieces: string[];
            message?: string;
            version: components["schemas"]["Version"];
        };
        /** @description Nouveau gestionnaire du dossier */
        Reaffectation: {
            gestionnaireId: string;
            motif?: string;
            version: components["schemas"]["Version"];
        };
        /** @description Motif de réouverture */
        Reouverture: {
            motif: string;
            version: components["schemas"]["Version"];
        };
        /** @description Événement de la chronologie d'un dossier */
        EvenementHistorique: {
            /** Format: date-time */
            horodatage: string;
            acteur?: components["schemas"]["Personne"];
            role?: string;
            action: string;
            detail?: string;
        };
        /** @description Page d'événements */
        PageHistorique: {
            elements: components["schemas"]["EvenementHistorique"][];
            curseurSuivant?: string | null;
        };
        /**
         * @description Nature de la pièce
         * @enum {string}
         */
        CategoriePiece: "PHOTO" | "DEVIS" | "FACTURE" | "CONSTAT" | "RAPPORT_EXPERTISE" | "AUTRE";
        /** @description Pièce justificative */
        Piece: {
            /** Format: uuid */
            id: string;
            nom: string;
            categorie?: components["schemas"]["CategoriePiece"];
            /** @example image/jpeg */
            typeDetecte: string;
            /**
             * Format: int64
             * @description Taille en octets
             */
            taille: number;
            /** @enum {string} */
            statutAnalyse: "EN_ANALYSE" | "SAINE" | "REJETEE";
            /** @description Rôle de la personne qui a déposé la pièce */
            deposeePar?: string;
            /** Format: date-time */
            deposeeLe: string;
        };
        /** @description Expert à missionner */
        CreationMission: {
            expertId: string;
            version: components["schemas"]["Version"];
        };
        /** @description Ligne du chiffrage de l'expert */
        LigneChiffrage: {
            poste: string;
            /**
             * @description Quantité décimale
             * @example 22
             */
            quantite: string;
            /** @example m² */
            unite?: string;
            prixUnitaire: components["schemas"]["Montant"];
            tauxVetuste: number;
            total?: components["schemas"]["Montant"];
        };
        /** @description Rapport d'expertise */
        Rapport: {
            constats?: string;
            lignes: components["schemas"]["LigneChiffrage"][];
            depose: boolean;
            /** Format: date-time */
            deposeLe?: string | null;
        };
        /** @description Contenu provisoire du rapport */
        BrouillonRapport: {
            constats?: string;
            /** Format: date-time */
            rendezVous?: string | null;
            lignes: components["schemas"]["LigneChiffrage"][];
        };
        /** @description Mission d'expertise */
        Mission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sinistreId: string;
            sinistreNumero: string;
            garantie?: components["schemas"]["TypeGarantie"];
            lieu?: components["schemas"]["Adresse"];
            /** @enum {string} */
            statut: "NOUVELLE" | "PLANIFIEE" | "RAPPORT_ATTENDU" | "DEPOSEE";
            /** Format: date-time */
            rendezVous?: string | null;
            rapport?: components["schemas"]["Rapport"];
        };
        /** @description Page de missions */
        PageMissions: {
            elements: components["schemas"]["Mission"][];
            curseurSuivant?: string | null;
        };
        /** @description Demande de calcul d'une proposition */
        CreationProposition: {
            version: components["schemas"]["Version"];
        };
        /** @description Ligne du détail de calcul de l'indemnité */
        LigneCalcul: {
            poste: string;
            /** @example Rapport d'expertise */
            source: string;
            montant: components["schemas"]["Montant"];
        };
        /** @description Proposition d'indemnité, puis offre faite à l'assuré */
        Proposition: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sinistreId: string;
            version: components["schemas"]["Version"];
            /** @enum {string} */
            statut: "BROUILLON" | "EN_VALIDATION" | "REJETEE" | "OFFRE_ENVOYEE" | "ACCEPTEE" | "CONTESTEE";
            lignes: components["schemas"]["LigneCalcul"][];
            dommageRetenu: components["schemas"]["Montant"];
            vetuste: components["schemas"]["Montant"];
            plafond: components["schemas"]["Montant"];
            franchise: components["schemas"]["Montant"];
            montant: components["schemas"]["Montant"];
            proposeePar?: components["schemas"]["Personne"];
            valideePar?: components["schemas"]["Personne"];
            messageAssure?: string;
            /** Format: date-time */
            offreEnvoyeeLe?: string | null;
            motifContestation?: string | null;
        };
        /** @description Page de propositions */
        PagePropositions: {
            elements: components["schemas"]["Proposition"][];
            curseurSuivant?: string | null;
        };
        /** @description Envoi de la proposition */
        EnvoiProposition: {
            messageAssure?: string;
            version: components["schemas"]["Version"];
        };
        /** @description Validation par un responsable */
        DecisionValidation: {
            commentaire?: string;
            version: components["schemas"]["Version"];
        };
        /** @description Rejet motivé par un responsable */
        Rejet: {
            commentaire: string;
            version: components["schemas"]["Version"];
        };
        /** @description Acceptation de l'offre par l'assuré */
        ReponseOffre: {
            version: components["schemas"]["Version"];
        };
        /** @description Contestation motivée de l'offre (RG-14) */
        Contestation: {
            motif: string;
            version: components["schemas"]["Version"];
        };
        /** @description Statut d'un ordre de virement */
        RetourPaiement: {
            ordreId: string;
            /** Format: uuid */
            propositionId: string;
            /** @enum {string} */
            statut: "EXECUTE" | "REJETE";
            /** Format: date-time */
            executeLe?: string | null;
            motifRejet?: string | null;
        };
        /** @description Charge d'un gestionnaire */
        ChargeGestionnaire: {
            gestionnaire: components["schemas"]["Personne"];
            total: number;
            sousCinqJours: number;
            enRetard: number;
        };
        /** @description Taux de décisions dans les délais pour une semaine */
        PointHebdomadaire: {
            /** @example 2026-W39 */
            semaine: string;
            /** Format: double */
            tauxDansLesDelais: number;
        };
        /** @description Indicateurs de pilotage */
        Indicateurs: {
            stockParStatut: {
                [key: string]: number;
            };
            enRetard: number;
            echeanceSousCinqJours: number;
            /** Format: double */
            delaiMoyenDecisionJours?: number;
            montantIndemniseMois?: components["schemas"]["Montant"];
            charge: components["schemas"]["ChargeGestionnaire"][];
            historique: components["schemas"]["PointHebdomadaire"][];
        };
        /** @description Paramètres des règles de gestion */
        Parametres: {
            seuilExpertise: components["schemas"]["Montant"];
            seuilDoubleValidation: components["schemas"]["Montant"];
            delaiDeclarationJoursOuvres: number;
            delaiDeclarationVolJoursOuvres: number;
            delaiReouvertureAns: number;
            delaiAccuseReceptionHeures: number;
            delaiDecisionJours: number;
            alerteAvantEcheanceJours: number;
            delaiClassementSansSuiteJours: number;
            delaiRelanceOffreJours: number;
            fraudeSinistresSur12Mois: number;
            fraudeDelaiApresSouscriptionJours: number;
            piecesTailleMaxMo: number;
            version: components["schemas"]["Version"];
        };
        /** @description Entrée du journal d'audit */
        EntreeAudit: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            horodatage: string;
            acteurId: string;
            acteurRole: string;
            action: string;
            objetType: string;
            /** Format: uuid */
            objetId: string;
            avant?: {
                [key: string]: unknown;
            } | null;
            apres?: {
                [key: string]: unknown;
            } | null;
        };
        /** @description Page du journal d'audit */
        PageAudit: {
            elements: components["schemas"]["EntreeAudit"][];
            curseurSuivant?: string | null;
        };
        /** @description Erreur au format RFC 9457 (Problem Details) */
        Probleme: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Règle de gestion concernée, par exemple RG-06
             * @example RG-06
             */
            regle?: string;
            /**
             * Format: int64
             * @description Présent en cas de conflit de version
             */
            versionActuelle?: number;
            /** @description Détail des champs invalides */
            erreurs?: {
                champ: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Dossier mis à jour */
        SinistreMisAJour: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Sinistre"];
            };
        };
        /** @description Proposition */
        PropositionMiseAJour: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Proposition"];
            };
        };
        /** @description Paramètres en vigueur */
        ParametresActuels: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Parametres"];
            };
        };
        /** @description Requête mal formée ou champ invalide */
        Invalide: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Authentification absente ou invalide */
        NonAuthentifie: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Action non permise pour cet utilisateur */
        Interdit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Ressource inexistante, ou hors du périmètre d'un assuré */
        Introuvable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Le dossier a été modifié entre-temps (RG-13) */
        ConflitDeVersion: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.claimflow.example/problemes/conflit-de-version",
                 *       "title": "Le dossier a été modifié entre-temps",
                 *       "status": 409,
                 *       "detail": "Version 7 attendue, la version actuelle est 8.",
                 *       "instance": "/api/v1/sinistres/0192a3c4-7f1e-7b21-9c55-2f4e8d1a6b30/recevabilite",
                 *       "versionActuelle": 8
                 *     }
                 */
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Fichier de plus de 10 Mo (RG-12) */
        TropVolumineux: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Type de fichier refusé (RG-12) */
        TypeNonSupporte: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
        /** @description Règle métier ou transition refusée */
        RegleMetierViolee: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.claimflow.example/problemes/regle-metier",
                 *       "title": "Rapport d'expertise requis",
                 *       "status": 422,
                 *       "detail": "L'estimation dépasse 1 500,00 € ; une proposition exige un rapport d'expertise.",
                 *       "regle": "RG-04"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Probleme"];
            };
        };
    };
    parameters: {
        /** @description Identifiant technique du dossier (UUID v7) */
        SinistreId: string;
        /** @description Identifiant de la pièce */
        PieceId: string;
        /** @description Identifiant de la mission d'expertise */
        MissionId: string;
        /** @description Identifiant de la proposition */
        PropositionId: string;
        /** @description Curseur opaque renvoyé par la page précédente */
        Curseur: string;
        /** @description Nombre d'éléments par page */
        Limite: number;
        /** @description Clé unique par déclaration, générée par le client ; conservée 24 heures */
        CleIdempotence: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listerMesContrats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contrats de l'assuré */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contrat"][];
                };
            };
            401: components["responses"]["NonAuthentifie"];
            403: components["responses"]["Interdit"];
        };
    };
    rechercherSinistres: {
        parameters: {
            query?: {
                /** @description Numéro de dossier ou nom de l'assuré, même partiel */
                texte?: string;
                /** @description Un ou plusieurs statuts */
                statut?: components["schemas"]["Statut"][];
                /** @description Type de garantie */
                garantie?: components["schemas"]["TypeGarantie"];
                /** @description Seulement les dossiers dont l'échéance de décision est dépassée */
                enRetard?: boolean;
                /** @description Curseur opaque renvoyé par la page précédente */
                curseur?: components["parameters"]["Curseur"];
                /** @description Nombre d'éléments par page */
                limite?: components["parameters"]["Limite"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page de dossiers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSinistres"];
                };
            };
            400: components["responses"]["Invalide"];
            401: components["responses"]["NonAuthentifie"];
        };
    };
    declarerSinistre: {
        parameters: {
            query?: never;
            header: {
                /** @description Clé unique par déclaration, générée par le client ; conservée 24 heures */
                "Idempotency-Key": components["parameters"]["CleIdempotence"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclarationSinistre"];
            };
        };
        responses: {
            /** @description Dossier créé */
            201: {
                headers: {
                    /** @description URL du dossier créé */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sinistre"];
                };
            };
            400: components["responses"]["Invalide"];
            401: components["responses"]["NonAuthentifie"];
            403: components["responses"]["Interdit"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    consulterSinistre: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dossier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sinistre"];
                };
            };
            401: components["responses"]["NonAuthentifie"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    deciderRecevabilite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRecevabilite"];
            };
        };
        responses: {
            200: components["responses"]["SinistreMisAJour"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    demanderPieces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandePieces"];
            };
        };
        responses: {
            200: components["responses"]["SinistreMisAJour"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    reaffecterSinistre: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reaffectation"];
            };
        };
        responses: {
            200: components["responses"]["SinistreMisAJour"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
        };
    };
    rouvrirSinistre: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reouverture"];
            };
        };
        responses: {
            200: components["responses"]["SinistreMisAJour"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    consulterHistorique: {
        parameters: {
            query?: {
                /** @description Curseur opaque renvoyé par la page précédente */
                curseur?: components["parameters"]["Curseur"];
                /** @description Nombre d'éléments par page */
                limite?: components["parameters"]["Limite"];
            };
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Événements du dossier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageHistorique"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    listerPieces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pièces du dossier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Piece"][];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    deposerPiece: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    fichier: string;
                    categorie?: components["schemas"]["CategoriePiece"];
                };
            };
        };
        responses: {
            /** @description Pièce reçue, analyse en cours */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Piece"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            413: components["responses"]["TropVolumineux"];
            415: components["responses"]["TypeNonSupporte"];
        };
    };
    telechargerPiece: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la pièce */
                pieceId: components["parameters"]["PieceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirection vers l'URL présignée */
            302: {
                headers: {
                    /** @description URL présignée du fichier */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    missionnerExpert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationMission"];
            };
        };
        responses: {
            /** @description Mission créée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    listerMesMissions: {
        parameters: {
            query?: {
                /** @description Curseur opaque renvoyé par la page précédente */
                curseur?: components["parameters"]["Curseur"];
                /** @description Nombre d'éléments par page */
                limite?: components["parameters"]["Limite"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Missions de l'expert */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageMissions"];
                };
            };
            403: components["responses"]["Interdit"];
        };
    };
    enregistrerBrouillonRapport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la mission d'expertise */
                missionId: components["parameters"]["MissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrouillonRapport"];
            };
        };
        responses: {
            /** @description Mission à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    deposerRapport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la mission d'expertise */
                missionId: components["parameters"]["MissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rapport déposé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    creerProposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant technique du dossier (UUID v7) */
                sinistreId: components["parameters"]["SinistreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationProposition"];
            };
        };
        responses: {
            /** @description Proposition créée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposition"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    consulterProposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la proposition */
                propositionId: components["parameters"]["PropositionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PropositionMiseAJour"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    envoyerProposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la proposition */
                propositionId: components["parameters"]["PropositionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvoiProposition"];
            };
        };
        responses: {
            200: components["responses"]["PropositionMiseAJour"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    listerValidationsEnAttente: {
        parameters: {
            query?: {
                /** @description Curseur opaque renvoyé par la page précédente */
                curseur?: components["parameters"]["Curseur"];
                /** @description Nombre d'éléments par page */
                limite?: components["parameters"]["Limite"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Propositions à valider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePropositions"];
                };
            };
            403: components["responses"]["Interdit"];
        };
    };
    validerProposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la proposition */
                propositionId: components["parameters"]["PropositionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionValidation"];
            };
        };
        responses: {
            200: components["responses"]["PropositionMiseAJour"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    rejeterProposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la proposition */
                propositionId: components["parameters"]["PropositionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rejet"];
            };
        };
        responses: {
            200: components["responses"]["PropositionMiseAJour"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
        };
    };
    accepterOffre: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la proposition */
                propositionId: components["parameters"]["PropositionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReponseOffre"];
            };
        };
        responses: {
            200: components["responses"]["PropositionMiseAJour"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    contesterOffre: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant de la proposition */
                propositionId: components["parameters"]["PropositionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Contestation"];
            };
        };
        responses: {
            200: components["responses"]["PropositionMiseAJour"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["ConflitDeVersion"];
            422: components["responses"]["RegleMetierViolee"];
        };
    };
    enregistrerRetourPaiement: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC-SHA256 du corps, encodé en hexadécimal */
                "X-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetourPaiement"];
            };
        };
        responses: {
            /** @description Retour enregistré */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Invalide"];
            401: components["responses"]["NonAuthentifie"];
        };
    };
    consulterIndicateurs: {
        parameters: {
            query?: {
                /** @description Profondeur de l'historique, en semaines */
                periodeSemaines?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicateurs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Indicateurs"];
                };
            };
            403: components["responses"]["Interdit"];
        };
    };
    consulterParametres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ParametresActuels"];
            403: components["responses"]["Interdit"];
        };
    };
    modifierParametres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Parametres"];
            };
        };
        responses: {
            200: components["responses"]["ParametresActuels"];
            400: components["responses"]["Invalide"];
            403: components["responses"]["Interdit"];
            409: components["responses"]["ConflitDeVersion"];
        };
    };
    consulterJournalAudit: {
        parameters: {
            query?: {
                /** @description Identifiant de l'objet concerné (dossier, pièce, proposition…) */
                objetId?: string;
                /** @description Identifiant de l'utilisateur */
                acteurId?: string;
                /** @description Type d'action */
                action?: string;
                /** @description Début de la période (inclus) */
                du?: string;
                /** @description Fin de la période (exclue) */
                au?: string;
                /** @description Curseur opaque renvoyé par la page précédente */
                curseur?: components["parameters"]["Curseur"];
                /** @description Nombre d'éléments par page */
                limite?: components["parameters"]["Limite"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entrées du journal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAudit"];
                };
            };
            403: components["responses"]["Interdit"];
        };
    };
}
